---
title: emailaddress.horse
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
plugins:
- jekyll-feed
- jekyll-gist
description: John Bannister's personal website.
author: John Bannister
permalink: "/:collection/:title"
