defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "article"

exclude:
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist

title: emailaddress.horse
description: John Bannister's personal website.
author: John Bannister
