---
title: emailaddress.horse
timezone: UTC
url: https://emailaddress.horse
collections:
  games:
    title: Games
    sort_by: title
  posts:
    title: Posts
    output: true
  habits:
    title: Habits
    output: false
    sort_by: title
defaults:
- scope:
    path: ''
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
plugins:
- jekyll-feed
- jekyll-gist
- jekyll-menus
description: John Bannister's personal website.
author: John Bannister
permalink: "/:collection/:title"
